#include "config.h"

#line 4 "lex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[180] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   87,   21,   18,   20,   19,   11,   21,   21,
       21,   21,   17,    6,    6,   21,   12,   21,   31,   28,
       29,   30,   31,   27,   22,   31,   72,   69,   71,   70,
       65,   32,   65,   72,   65,   65,   72,   66,   33,   65,
       67,   65,   72,   50,   50,   68,   65,   72,   65,   72,
       36,   72,   65,   35,   34,   37,   37,   37,   37,   83,
       85,   84,   73,   77,   86,   18,   20,   17,    7,    1,
       13,    0,   10,   17,    4,    6,    0,    0,    0,    3,
       12,   15,    0,   28,   29,   27,   23,    0,   27,   22,

       25,    0,   69,   68,   62,   51,   45,   63,    0,   54,
       41,   42,   55,   56,   48,   50,   43,   44,   43,    0,
        0,   68,   57,   59,   61,   60,   58,   47,   36,   39,
        0,   64,   37,   37,   37,   37,   37,   37,   37,   37,
       37,   37,   83,   76,   74,    0,   82,   78,   80,   81,
       82,    0,    9,    2,    5,    8,    0,    0,    0,    0,
       53,   46,   49,   52,    0,   37,   37,   37,    0,    0,
       14,   16,   24,   26,   38,   40,   75,   79,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    9,   10,   11,    7,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   21,   21,   21,   21,   22,   22,    7,   23,   24,
       25,   26,    7,   27,   28,   29,   28,   28,   28,   30,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   31,
        7,   32,   12,    7,   31,    1,   28,   33,   28,   28,

       28,   30,   31,   31,   31,   31,   31,   31,   31,   34,
       35,   31,   31,   36,   31,   31,   31,   31,   31,   37,
       31,   31,   38,   39,   40,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[41] =
    {   0,
        1,    1,    2,    3,    1,    3,    1,    1,    1,    4,
        1,    1,    1,    1,    1,    1,    5,    3,    6,    6,
        6,    6,    1,    1,    1,    1,    1,    7,    7,    7,
        5,    3,    7,    5,    5,    5,    5,    8,    1,    1
    } ;

static const flex_int16_t yy_base[198] =
    {   0,
        0,    0,   39,   75,  112,    0,   38,   39,  147,    0,
      153,  183,  233,  562,   78,  562,  562,  562,    0,   27,
       44,    0,    0,  197,   39,   34,    0,  175,  562,  188,
      562,  562,  183,    0,    0,  187,  562,  156,  562,  562,
      189,  562,  562,    0,   64,  160,    0,  562,  562,  198,
      562,  172,   67,  218,  239,    0,   68,   77,   69,  153,
        0,  207,   51,  562,  562,  222,  256,  246,    0,    0,
      562,  562,  562,  182,  275,  297,  562,    0,    0,   77,
      562,  282,   39,    0,  286,  295,   80,  203,    0,  243,
        0,  562,  302,  247,  562,    0,  562,  306,    0,    0,

      562,  310,  208,    0,  562,    0,  135,  562,  314,   37,
      562,  562,  318,  322,  326,    0,  562,  562,  142,  329,
        0,    0,  562,  562,  562,  562,  562,  332,    0,  562,
      335,  562,    0,  339,    0,  329,    0,    0,    0,  180,
      348,  353,    0,  562,  562,  357,  562,  562,  562,  562,
      372,  376,  562,  299,  380,    0,  383,  387,  391,  398,
      562,  395,  405,    0,  413,  402,    0,    0,  420,  424,
      562,  562,  562,  562,  562,  562,  562,  562,  562,  464,
      472,  475,  482,  490,  494,  501,  505,  507,  514,  522,
      526,  529,  536,  541,  549,  552,  554

    } ;

static const flex_int16_t yy_def[198] =
    {   0,
      179,    1,  180,  180,  179,    5,    5,    5,    5,    9,
      181,  181,  179,  179,  179,  179,  179,  179,  182,  179,
      179,  183,  184,  179,  179,  179,  185,  179,  179,  179,
      179,  179,  179,  186,  187,  179,  179,  179,  179,  179,
      179,  179,  179,  188,  179,  179,  189,  179,  179,  179,
      179,  179,  179,  179,  179,  190,  179,  179,  179,  179,
      191,  179,  179,  179,  179,  192,  179,   67,  192,  193,
      179,  179,  179,  194,  195,  179,  179,  184,  182,  179,
      179,  179,  179,  184,  179,  179,  179,  179,  196,  179,
      185,  179,  179,  179,  179,  186,  179,  179,  186,  187,

      179,  179,  179,  190,  179,  188,  179,  179,  179,  179,
      179,  179,  179,  179,   55,   55,  179,  179,  179,  179,
      197,  190,  179,  179,  179,  179,  179,  179,  191,  179,
      179,  179,  192,  192,  134,   67,   68,  192,  192,  192,
      192,  179,  193,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  196,  179,  179,  179,  179,
      179,  179,  179,  197,  179,  192,  141,  142,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,    0,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179

    } ;

static const flex_int16_t yy_nxt[603] =
    {   0,
       14,   15,   16,   17,   18,   14,   14,   19,   20,   21,
       22,   14,   23,   14,   14,   14,   14,   14,   24,   25,
       25,   25,   23,   14,   14,   14,   26,   27,   27,   27,
       27,   28,   27,   27,   27,   27,   27,   14,   14,   14,
       30,   31,   32,   37,   37,   80,   80,  161,   33,  153,
       64,   64,   90,   90,   90,   65,   65,   86,   86,   86,
       86,   34,   81,   81,   81,   81,   35,   35,   35,   35,
       36,   35,   35,   35,   35,   35,   30,   31,   32,   76,
       77,   82,  107,  107,   33,  113,  113,  113,  113,  132,
       78,  123,  124,  126,  127,   80,   80,   34,  154,  154,

       78,  125,   35,   35,   35,   35,   36,   35,   35,   35,
       35,   35,   37,   38,   39,   40,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   42,
       54,   55,   55,   55,   56,   57,   58,   59,   60,   61,
       61,   61,   61,   62,   61,   61,   61,   61,   61,   37,
       63,   37,   37,  107,  107,   71,   72,  103,   73,   64,
      162,  162,   74,   66,   65,   67,   68,   68,   68,  108,
       73,  128,  128,  128,   69,   69,   69,   69,  104,   69,
       69,   69,   69,   69,   75,   71,   72,  112,   73,   94,
       95,  144,   74,   92,   92,   92,   92,  109,  166,  166,

       73,   97,   97,   97,   97,  101,  101,  101,  101,  103,
       96,  111,   93,  105,   75,   85,   85,   85,   86,  146,
       98,  155,  155,  155,  102,  130,  130,  130,  130,   87,
      104,   88,  179,   89,  114,  179,  115,  115,  115,  116,
      134,  134,  134,  134,  131,  179,  117,  118,   94,   95,
      119,  179,  120,  179,  121,  114,  179,  116,  116,  116,
      116,   90,   90,   90,  137,  137,  137,  117,  118,   96,
      179,  117,  135,  179,  136,  136,  136,  137,  138,  179,
      133,  179,  133,  133,  138,  139,  133,  179,  140,  133,
      141,  133,  142,  148,  148,  148,  148,  179,   76,   77,

      152,  152,  152,  152,   85,   85,   85,   86,  149,   78,
      150,  179,  151,   86,   86,   86,   86,  154,  154,   78,
      157,  157,  157,  157,  158,  158,  158,  158,  159,  159,
      159,  159,  160,  160,  160,  160,  113,  113,  113,  113,
      113,  113,  113,  113,  115,  115,  115,  163,  163,  163,
      128,  128,  128,  165,  165,  165,  165,  134,  134,  134,
      134,  138,  179,  133,  179,  133,  167,  167,  167,  133,
      179,  168,  168,  168,  168,  169,  169,  169,  169,  179,
      168,  168,  168,  133,  179,  168,  133,  133,  133,  133,
      170,  170,  170,  170,  152,  152,  152,  152,  155,  155,

      155,  157,  157,  157,  157,  158,  158,  158,  158,  159,
      159,  159,  159,  162,  162,  171,  160,  160,  160,  160,
      166,  166,  172,  163,  163,  163,  173,  179,  179,  179,
      174,  165,  165,  165,  165,  179,  179,  175,  169,  169,
      169,  169,  170,  170,  170,  170,  179,  179,  179,  179,
      179,  179,  176,  179,  179,  179,  179,  179,  179,  177,
      179,  179,  179,  178,   29,   29,   29,   29,   29,   29,
       29,   29,   70,   70,   70,   70,   70,   70,   70,   70,
       79,   79,   83,  179,   83,   83,   83,   83,   83,   83,
       84,  179,   84,   84,   84,   84,   84,   84,   91,   91,

       91,   99,  179,   99,   99,   99,   99,   99,   99,  100,
      100,  100,  106,  106,  110,  179,  110,  110,  110,  110,
      110,  110,  122,  179,  122,  122,  122,  122,  122,  122,
      129,  129,  129,  133,  133,  133,  143,  179,  179,  179,
      143,  143,  143,  143,  145,  179,  145,  179,  145,  147,
      179,  147,  147,  147,  147,  147,  147,  156,  156,  164,
      164,   13,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,

      179,  179
    } ;

static const flex_int16_t yy_chk[603] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    3,    7,    8,   20,   20,  110,    3,   83,
        7,    8,   26,   26,   26,    7,    8,   25,   25,   25,
       25,    3,   21,   21,   21,   21,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    4,    4,    4,   15,
       15,   21,   45,   45,    4,   53,   53,   53,   53,   63,
       15,   57,   57,   59,   59,   80,   80,    4,   87,   87,

       15,   58,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    9,  107,  107,   11,   11,   38,   11,    9,
      119,  119,   11,    9,    9,    9,    9,    9,    9,   46,
       11,   60,   60,   60,    9,    9,    9,    9,   38,    9,
        9,    9,    9,    9,   11,   12,   12,   52,   12,   30,
       30,   74,   12,   28,   28,   28,   28,   46,  140,  140,

       12,   33,   33,   33,   33,   36,   36,   36,   36,  103,
       30,   50,   28,   41,   12,   24,   24,   24,   24,   74,
       33,   88,   88,   88,   36,   62,   62,   62,   62,   24,
      103,   24,   13,   24,   54,    0,   54,   54,   54,   54,
       66,   66,   66,   66,   62,    0,   54,   54,   94,   94,
       54,    0,   54,    0,   54,   55,    0,   55,   55,   55,
       55,   90,   90,   90,   68,   68,   68,   55,   55,   94,
        0,   55,   67,    0,   67,   67,   67,   67,   68,    0,
       68,    0,   68,   67,   67,   67,   67,    0,   67,   67,
       67,   67,   67,   75,   75,   75,   75,    0,   76,   76,

       82,   82,   82,   82,   85,   85,   85,   85,   75,   76,
       75,    0,   75,   86,   86,   86,   86,  154,  154,   76,
       93,   93,   93,   93,   98,   98,   98,   98,  102,  102,
      102,  102,  109,  109,  109,  109,  113,  113,  113,  113,
      114,  114,  114,  114,  115,  115,  115,  120,  120,  120,
      128,  128,  128,  131,  131,  131,  131,  134,  134,  134,
      134,  136,    0,  136,    0,  136,  141,  141,  141,  142,
        0,  142,  142,  142,  142,  146,  146,  146,  146,    0,
      142,  142,  142,  142,    0,  142,  142,  142,  142,  142,
      151,  151,  151,  151,  152,  152,  152,  152,  155,  155,

      155,  157,  157,  157,  157,  158,  158,  158,  158,  159,
      159,  159,  159,  162,  162,  152,  160,  160,  160,  160,
      166,  166,  157,  163,  163,  163,  158,    0,    0,    0,
      159,  165,  165,  165,  165,    0,    0,  160,  169,  169,
      169,  169,  170,  170,  170,  170,    0,    0,    0,    0,
        0,    0,  165,    0,    0,    0,    0,    0,    0,  169,
        0,    0,    0,  170,  180,  180,  180,  180,  180,  180,
      180,  180,  181,  181,  181,  181,  181,  181,  181,  181,
      182,  182,  183,    0,  183,  183,  183,  183,  183,  183,
      184,    0,  184,  184,  184,  184,  184,  184,  185,  185,

      185,  186,    0,  186,  186,  186,  186,  186,  186,  187,
      187,  187,  188,  188,  189,    0,  189,  189,  189,  189,
      189,  189,  190,    0,  190,  190,  190,  190,  190,  190,
      191,  191,  191,  192,  192,  192,  193,    0,    0,    0,
      193,  193,  193,  193,  194,    0,  194,    0,  194,  195,
        0,  195,  195,  195,  195,  195,  195,  196,  196,  197,
      197,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,

      179,  179
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lex.l"

#line 6 "lex.l"
/*

6809 assembly scanner

Copyright 2013-2025 Ciaran Anscomb

This file is part of asm6809.

asm6809 is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free
Software Foundation, either version 3 of the License, or (at your option)
any later version.

See COPYING.GPL for redistribution conditions.

*/

#include <stdio.h>
#include <string.h>

#include "xalloc.h"

#include "error.h"
#include "register.h"
#include "slist.h"

#include "grammar.h"

static int delim;

static int id_or_reg(void);
static int read_line(char *buf, int max_size);

char *lex_fetch_line(void);
void lex_free_all(void);

#define YY_INPUT(buf,result,max_size) \
	{ result = read_line(buf, max_size); }

#line 681 "lex.c"
#define YY_NO_INPUT 1

#line 684 "lex.c"

#define INITIAL 0
#define opcode 1
#define arg 2
#define argnostr 3
#define argnostrnum 4
#define string 5

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 68 "lex.l"


#line 907 "lex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 180 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 562 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 72 "lex.l"
{ yylval.as_int = strtoimax(yytext+1, NULL, 2); return INTEGER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 73 "lex.l"
{ yylval.as_int = strtoimax(yytext+2, NULL, 2); return INTEGER; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 74 "lex.l"
{ yylval.as_int = strtoimax(yytext+1, NULL, 8); return INTEGER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "lex.l"
{ yylval.as_int = strtoimax(yytext, NULL, 8); return INTEGER; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 76 "lex.l"
{ yylval.as_int = strtoimax(yytext+2, NULL, 8); return INTEGER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 77 "lex.l"
{ yylval.as_int = strtoimax(yytext, NULL, 10); return INTEGER; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 78 "lex.l"
{ yylval.as_int = strtoimax(yytext+1, NULL, 16); return INTEGER; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 79 "lex.l"
{ yylval.as_int = strtoimax(yytext+2, NULL, 16); return INTEGER; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 80 "lex.l"
{ yylval.as_int = *(yytext+1); return INTEGER; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 81 "lex.l"
{ yylval.as_int = *(yytext+1); return INTEGER; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 82 "lex.l"
{ yylval.as_int = 0; return INTEGER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "lex.l"
{ return id_or_reg(); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 90 "lex.l"
/* ";" or "*" introduces comment to end of line */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 91 "lex.l"
{ BEGIN(opcode); return WS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 92 "lex.l"
/* skip CR */
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 93 "lex.l"
{ return '\n'; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 94 "lex.l"
{ return *yytext; }
	YY_BREAK


case 22:
YY_RULE_SETUP
#line 100 "lex.l"
{ return id_or_reg(); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 104 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "lex.l"
/* ";" introduces comment to end of line */
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "lex.l"
{ BEGIN(arg); return WS; }
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 109 "lex.l"
{ BEGIN(INITIAL); return '\n'; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "lex.l"
/* skip CR */
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "lex.l"
{ BEGIN(INITIAL); return *yytext; }
	YY_BREAK


case 32:
YY_RULE_SETUP
#line 117 "lex.l"
{
			delim = *yytext;
			BEGIN(string);
			return DELIM;
		}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "lex.l"
{ BEGIN(argnostr); return *yytext; }
	YY_BREAK


case 34:
YY_RULE_SETUP
#line 129 "lex.l"
{ BEGIN(argnostr); return *yytext; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 130 "lex.l"
{ BEGIN(arg); return *yytext; }
	YY_BREAK


case 36:
YY_RULE_SETUP
#line 136 "lex.l"
{ BEGIN(argnostr); return id_or_reg(); }
	YY_BREAK


case 37:
YY_RULE_SETUP
#line 142 "lex.l"
{ BEGIN(argnostrnum); yylval.as_string = strndup(yytext, yyleng); return ID; }
	YY_BREAK


case 38:
YY_RULE_SETUP
#line 148 "lex.l"
{ BEGIN(argnostrnum); yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 149 "lex.l"
{ BEGIN(argnostrnum); yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 150 "lex.l"
{ BEGIN(argnostrnum); yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 152 "lex.l"
{ BEGIN(argnostr); return INC2; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 153 "lex.l"
{ BEGIN(argnostr); return DEC2; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 155 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext, NULL, 10); return BACKREF; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 156 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext, NULL, 10); return FWDREF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 158 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+1, NULL, 2); return INTEGER; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 159 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+2, NULL, 2); return INTEGER; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 160 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+1, NULL, 8); return INTEGER; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 161 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext, NULL, 8); return INTEGER; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 162 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+2, NULL, 8); return INTEGER; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext, NULL, 10); return INTEGER; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 164 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+1, NULL, 16); return INTEGER; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 165 "lex.l"
{ BEGIN(argnostr); yylval.as_int = strtoimax(yytext+2, NULL, 16); return INTEGER; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 166 "lex.l"
{ BEGIN(argnostr); yylval.as_int = *(yytext+1); return INTEGER; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 167 "lex.l"
{ BEGIN(argnostr); yylval.as_int = *(yytext+1); return INTEGER; }
	YY_BREAK
case 55:
#line 169 "lex.l"
case 56:
YY_RULE_SETUP
#line 169 "lex.l"
{ BEGIN(argnostr); yylval.as_float = strtod(yytext, NULL); return FLOAT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 171 "lex.l"
{ BEGIN(arg); return SHL; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 172 "lex.l"
{ BEGIN(arg); return SHR; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 174 "lex.l"
{ BEGIN(arg); return LE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 175 "lex.l"
{ BEGIN(arg); return GE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 176 "lex.l"
{ BEGIN(arg); return EQ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 177 "lex.l"
{ BEGIN(arg); return NE; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 178 "lex.l"
{ BEGIN(arg); return LAND; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 179 "lex.l"
{ BEGIN(arg); return LOR; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 181 "lex.l"
{ BEGIN(arg); return *yytext; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 182 "lex.l"
{ BEGIN(argnostr); return *yytext; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 184 "lex.l"
{ BEGIN(arg); return *yytext; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 186 "lex.l"
/* ";" introduces comment to end of line */
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 187 "lex.l"
/* skip whitespace */
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 188 "lex.l"
/* skip CR */
	YY_BREAK
case 71:
/* rule 71 can match eol */
YY_RULE_SETUP
#line 189 "lex.l"
{ BEGIN(INITIAL); return *yytext; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 190 "lex.l"
{ return *yytext; }
	YY_BREAK


case 73:
YY_RULE_SETUP
#line 196 "lex.l"
{
			if (*yytext == delim) {
				BEGIN(argnostr);
				return DELIM;
			} else {
				yylval.as_string = strndup(yytext, yyleng);
				return TEXT;
			}
		}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 206 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 207 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 76:
#line 209 "lex.l"
case 77:
YY_RULE_SETUP
#line 209 "lex.l"
{ yylval.as_string = strndup("&", 1); return TEXT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 210 "lex.l"
{ yylval.as_string = strndup(yytext+1, yyleng-1); return INTERP; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 211 "lex.l"
{ yylval.as_string = strndup(yytext+2, yyleng-3); return INTERP; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 213 "lex.l"
{ yylval.as_string = strndup("\n", 1); return TEXT; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 214 "lex.l"
{ yylval.as_string = strndup("\r", 1); return TEXT; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 215 "lex.l"
{ yylval.as_string = strndup(yytext+1, 1); return TEXT; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 217 "lex.l"
{ yylval.as_string = strndup(yytext, yyleng); return TEXT; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 219 "lex.l"
/* skip CR */
	YY_BREAK
case 85:
/* rule 85 can match eol */
YY_RULE_SETUP
#line 220 "lex.l"
{ BEGIN(INITIAL); return '\n'; }
	YY_BREAK

case 86:
YY_RULE_SETUP
#line 224 "lex.l"
ECHO;
	YY_BREAK
#line 1419 "lex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(opcode):
case YY_STATE_EOF(arg):
case YY_STATE_EOF(argnostr):
case YY_STATE_EOF(argnostrnum):
case YY_STATE_EOF(string):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 180 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 180 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 179);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 224 "lex.l"


static int id_or_reg(void) {
	enum reg_id r = reg_name_to_id(yytext);
	if (r != REG_INVALID) {
		yylval.as_reg = r;
		return REGISTER;
	}
	yylval.as_string = strndup(yytext, yyleng);
	return ID;
}

/*
 * Redefining YY_INPUT above, flex reads a line at a time.  Copies of lines are
 * cached, to be fetched by the grammar parser and associated with the parsed
 * data.
 */

static struct slist *lines = NULL;
static char *line = NULL;
static int line_length = 0;
static _Bool need_eol = 1;

static int read_line(char *buf, int max_size) {
	if (!yyin)
		return YY_NULL;
	char *r = fgets(buf, max_size, yyin);
	if (!r) {
		if (!feof(yyin)) {
			error_report(error_type_fatal, "scanner read failed");
		}
		if (need_eol) {
			buf[0] = '\n';
			buf[1] = 0;
		} else {
			if (line) {
				free(line);
				line = NULL;
				line_length = 0;
			}
			return YY_NULL;
		}
	}

	int len = strlen(buf);
	if (len > 1 && buf[len-1] == '\n' && buf[len-2] == '\r') {
		buf[len-2] = '\n';
		len--;
	}
	line = xrealloc(line, line_length + len + 1);
	memcpy(line + line_length, buf, len + 1);
	line_length = line_length + len;
	need_eol = 1;

	if (line_length > 0 && line[line_length-1] == '\n') {
		need_eol = 0;
		line[line_length-1] = 0;
		lines = slist_append(lines, line);
		line = NULL;
		line_length = 0;
	}

	return len;
}

char *lex_fetch_line(void) {
	if (!lines) {
		error_report(error_type_fatal, "internal: line copy fetched before ready");
		return NULL;
	}
	char *l = lines->data;
	lines = slist_remove(lines, l);
	return l;
}

void lex_free_all(void) {
	while (lines) {
		char *l = lines->data;
		lines = slist_remove(lines, l);
		free(l);
	}
	yylex_destroy();
}

